menu:
  mainmenu:
  - identifier: 2c360252-86f6-4f40-b9f7-fef75e7059ca
    name: empty resource
    url: content/empty-resource.md
    weight: 0
  - identifier: c65a943e-c3d5-4c30-85ba-9499bc770826
    name: resource 2
    url: content/resource-2.md
    weight: 10
